### ISSUE TITLE
Provide open source license file, mention in Readme, add headers to source code

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/SwaggerParser#19]
We should include the EPL (Eclipse Public License), same as our other projects, and specify in our readme that this is the license.

We should also use the Eclipse utility to add the code header.

**Comment by andylowry** [comment]
Merged in https://github.com/RepreZen/SwaggerParser/pull/22

**Comment by andylowry** [comment]
Note that I independently added headers to all files in task/5 branch after merging these changes from master into that branch. Going forward we should take care to keep these all updated.
